import type { Player } from "./types";

/**
 * Offline fallback for `GET /api/players`.
 *
 * The endpoint named in the assessment (`www.balldontlie.io/api/v1/players`)
 * has been retired and returns 404; its replacement (`api.balldontlie.io/v1`)
 * requires an API key. This fixture keeps the feature fully demonstrable when
 * no key is configured - see README.
 */
type Seed = readonly [first: string, last: string, position: string, team: string];

const SEEDS: readonly Seed[] = [
  ["Trae", "Young", "G", "Atlanta Hawks"],
  ["Jalen", "Johnson", "F", "Atlanta Hawks"],
  ["Onyeka", "Okongwu", "C", "Atlanta Hawks"],
  ["Jayson", "Tatum", "F", "Boston Celtics"],
  ["Jaylen", "Brown", "G-F", "Boston Celtics"],
  ["Derrick", "White", "G", "Boston Celtics"],
  ["Cam", "Thomas", "G", "Brooklyn Nets"],
  ["Nic", "Claxton", "C", "Brooklyn Nets"],
  ["LaMelo", "Ball", "G", "Charlotte Hornets"],
  ["Brandon", "Miller", "F", "Charlotte Hornets"],
  ["Mark", "Williams", "C", "Charlotte Hornets"],
  ["Coby", "White", "G", "Chicago Bulls"],
  ["Nikola", "Vucevic", "C", "Chicago Bulls"],
  ["Donovan", "Mitchell", "G", "Cleveland Cavaliers"],
  ["Darius", "Garland", "G", "Cleveland Cavaliers"],
  ["Evan", "Mobley", "F", "Cleveland Cavaliers"],
  ["Luka", "Doncic", "G", "Dallas Mavericks"],
  ["Kyrie", "Irving", "G", "Dallas Mavericks"],
  ["Daniel", "Gafford", "C", "Dallas Mavericks"],
  ["Nikola", "Jokic", "C", "Denver Nuggets"],
  ["Jamal", "Murray", "G", "Denver Nuggets"],
  ["Michael", "Porter Jr.", "F", "Denver Nuggets"],
  ["Cade", "Cunningham", "G", "Detroit Pistons"],
  ["Jalen", "Duren", "C", "Detroit Pistons"],
  ["Stephen", "Curry", "G", "Golden State Warriors"],
  ["Draymond", "Green", "F", "Golden State Warriors"],
  ["Jonathan", "Kuminga", "F", "Golden State Warriors"],
  ["Alperen", "Sengun", "C", "Houston Rockets"],
  ["Jalen", "Green", "G", "Houston Rockets"],
  ["Amen", "Thompson", "G-F", "Houston Rockets"],
  ["Tyrese", "Haliburton", "G", "Indiana Pacers"],
  ["Pascal", "Siakam", "F", "Indiana Pacers"],
  ["Myles", "Turner", "C", "Indiana Pacers"],
  ["Kawhi", "Leonard", "F", "LA Clippers"],
  ["James", "Harden", "G", "LA Clippers"],
  ["Ivica", "Zubac", "C", "LA Clippers"],
  ["LeBron", "James", "F", "Los Angeles Lakers"],
  ["Anthony", "Davis", "F-C", "Los Angeles Lakers"],
  ["Austin", "Reaves", "G", "Los Angeles Lakers"],
  ["Ja", "Morant", "G", "Memphis Grizzlies"],
  ["Jaren", "Jackson Jr.", "F", "Memphis Grizzlies"],
  ["Desmond", "Bane", "G", "Memphis Grizzlies"],
  ["Bam", "Adebayo", "C", "Miami Heat"],
  ["Tyler", "Herro", "G", "Miami Heat"],
  ["Giannis", "Antetokounmpo", "F", "Milwaukee Bucks"],
  ["Damian", "Lillard", "G", "Milwaukee Bucks"],
  ["Brook", "Lopez", "C", "Milwaukee Bucks"],
  ["Anthony", "Edwards", "G", "Minnesota Timberwolves"],
  ["Rudy", "Gobert", "C", "Minnesota Timberwolves"],
  ["Jaden", "McDaniels", "F", "Minnesota Timberwolves"],
  ["Zion", "Williamson", "F", "New Orleans Pelicans"],
  ["Brandon", "Ingram", "F", "New Orleans Pelicans"],
  ["Jalen", "Brunson", "G", "New York Knicks"],
  ["Karl-Anthony", "Towns", "C", "New York Knicks"],
  ["OG", "Anunoby", "F", "New York Knicks"],
  ["Shai", "Gilgeous-Alexander", "G", "Oklahoma City Thunder"],
  ["Chet", "Holmgren", "C", "Oklahoma City Thunder"],
  ["Jalen", "Williams", "F", "Oklahoma City Thunder"],
  ["Paolo", "Banchero", "F", "Orlando Magic"],
  ["Franz", "Wagner", "F", "Orlando Magic"],
  ["Joel", "Embiid", "C", "Philadelphia 76ers"],
  ["Tyrese", "Maxey", "G", "Philadelphia 76ers"],
  ["Paul", "George", "F", "Philadelphia 76ers"],
  ["Devin", "Booker", "G", "Phoenix Suns"],
  ["Kevin", "Durant", "F", "Phoenix Suns"],
  ["Bradley", "Beal", "G", "Phoenix Suns"],
  ["Anfernee", "Simons", "G", "Portland Trail Blazers"],
  ["Shaedon", "Sharpe", "G", "Portland Trail Blazers"],
  ["De'Aaron", "Fox", "G", "Sacramento Kings"],
  ["Domantas", "Sabonis", "C", "Sacramento Kings"],
  ["Keegan", "Murray", "F", "Sacramento Kings"],
  ["Victor", "Wembanyama", "C", "San Antonio Spurs"],
  ["Devin", "Vassell", "G", "San Antonio Spurs"],
  ["Jeremy", "Sochan", "F", "San Antonio Spurs"],
  ["Scottie", "Barnes", "F", "Toronto Raptors"],
  ["RJ", "Barrett", "G-F", "Toronto Raptors"],
  ["Immanuel", "Quickley", "G", "Toronto Raptors"],
  ["Lauri", "Markkanen", "F", "Utah Jazz"],
  ["Walker", "Kessler", "C", "Utah Jazz"],
  ["Jordan", "Poole", "G", "Washington Wizards"],
  ["Kyle", "Kuzma", "F", "Washington Wizards"],
  ["Alex", "Sarr", "C", "Washington Wizards"],
];

/** Ids are positional, so a player keeps the same id across restarts. */
export const FIXTURE_PLAYERS: readonly Player[] = SEEDS.map(
  ([firstName, lastName, position, nbaTeam], index) => ({
    id: index + 1,
    firstName,
    lastName,
    position,
    nbaTeam,
  }),
);
